language: node_js

node_js:
  "7"

cache:
  directories:
    - "node_modules"

env:
  - TEST_SUITE=unit
  - TEST_SUITE=acceptance

script: "case $TEST_SUITE in 'unit') npm test ;; 'acceptance') ng e2e ;; esac"

before_install:
  - npm i -g npm@4.2.0
