language: node_js

node_js:
  "7"

cache:
  directories:
    - "node_modules"

env:
  - TEST_SUITE=unit
  - TEST_SUITE=acceptance

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: "case $TEST_SUITE in 'unit') npm test ;; 'acceptance') ng e2e ;; esac"

before_install:
  - npm i -g npm@4.2.0
